#!/bin/bash -e

if [ "$1" = "configure" ]; then
    # remove link to configuration
    rm /etc/django/pyqounter/settings.py
    rm /etc/django/pyqounter/django.wsgi

    # virtual domain
    grep -v pyqounter < /etc/hosts > /etc/hosts.tmp
    mv /etc/hosts.tmp /etc/hosts

    # disable apache virtualhost
    a2dissite pyqounter
    invoke-rc.d apache2 reload
    
    mv /etc/apache2/sites-available/pyqounter /etc/apache2/sites-available/pyqounter.old
fi
