#!/bin/bash -e

if [ "$1" = "configure" ]; then
    # create link to configuration
    ln -s /usr/lib/rad/pyqounter-server/settings_local.py /etc/django/pyqounter/settings.py
    ln -s /usr/lib/rad/pyqounter-server/django.wsgi /etc/django/pyqounter/django.wsgi

    # virtual domain
    echo "127.0.0.1		pyqounter" >> /etc/hosts

    cat > /etc/apache2/sites-available/pyqounter <<EOF
<VirtualHost *>
	ServerAdmin ruslan.popov@gmail.com
	ServerName pyqounter

	WSGIScriptAlias / /etc/django/pyqounter/django.wsgi
	WSGIDaemonProcess pyqounter processes=10 maximum-requests=50 threads=1
	WSGIProcessGroup pyqounter

	LogLevel debug
	ErrorLog /var/log/apache2/error-pyqounter.log
	CustomLog /var/log/apache2/access-pyqounter.log combined
	ServerSignature On

	Alias /adminmedia/	"/usr/share/python-support/python-django/django/contrib/admin/media/"
</VirtualHost>
EOF

    # enable apache virtualhost
    a2ensite pyqounter
    invoke-rc.d apache2 reload
fi
