#!/bin/bash -e

PROJECT_DIR=/usr/lib/rad/pyqounter-server
CONFIG_DIR=/etc/django/pyqounter

case "$1" in

    configure)
	# Configure this package.  If the package must prompt the user for
	# information, do it here.

	# create link to configuration
	ln -s ${PROJECT_DIR}/settings_local.py ${CONFIG_DIR}/settings.py
	ln -s ${PROJECT_DIR}/django.wsgi ${CONFIG_DIR}/django.wsgi

	# virtual domain
	echo "127.0.0.1		pyqounter" >> /etc/hosts

	cat > /etc/apache2/sites-available/pyqounter <<EOF
<VirtualHost *>
	ServerAdmin ruslan.popov@gmail.com
	ServerName pyqounter

	WSGIScriptAlias / /etc/django/pyqounter/django.wsgi
	WSGIDaemonProcess pyqounter processes=10 maximum-requests=50 threads=1
	WSGIProcessGroup pyqounter

	LogLevel debug
	ErrorLog /var/log/apache2/error-pyqounter.log
	CustomLog /var/log/apache2/access-pyqounter.log combined
	ServerSignature On

	Alias /adminmedia/	"/usr/share/python-support/python-django/django/contrib/admin/media/"
</VirtualHost>
EOF

	# enable apache virtualhost
	a2ensite pyqounter
	invoke-rc.d apache2 reload

	echo '----------------------------------------------------'
	echo '  Do not forget to create database and run SYNCDB!  '
	echo '----------------------------------------------------'
	echo "CREATE USER pyqounter@localhost IDENTIFIED BY 'XXX';"
	echo "CREATE DATABASE pyqounter;"
	echo "GRANT ALL ON pyqounter.* TO pyqounter@localhost;"
	echo '----------------------------------------------------'

	;;

    *) 
	echo "$0: didn't understand being called with \`$1'" 1>&2

	;;

esac

exit 0;
